name: SignEditor
main: Coline\SignEditor\SignEditorMain
version: 3.0
api: [2.0.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
author: Coline Team (aquaminer)
website: PMine.ru