name: SignEditor
main: Coline\SignEditor\SignEditorMain
version: 1.0
api: [2.0.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
author: ColineTeam (aquaminer)
website: PMine.ru
commands:
    signedit:
        aliases: [sedit]